export { default as Home } from "../components/Header";
export { default as Login } from "../components/Login";
export { default as SignUp } from "../components/SignUp";
export { default as HomePage2 } from "../components/Homepage/Homepage2";
export { default as FoodlyStore } from "../components/FoodlyStore";
export { default as Products } from "../components/products/Products";
export { default as Blog } from "../components/Blog/Blog";
export { default as Recipes } from "../components/Recipes/Recipes";
export { default as Pages } from "../components/Pageses/Pages";
